### ISSUE TITLE
 Sub-optimal performance with repartitions

### ISSUE THREAD

**Issue by de-grave** [mpinese/mgrb-manuscript#2]
Repartition causes a full shuffle of the data [1]. With big number of annotations vds it creates a lot of unnecessary work and results in sub-optimal performance.

Elimination of repartitions in 05h_add_db_vep_variant_annots.py alone speeds up this phase 6 times (from 1 hour to ~10 minutes on 1GB uncompressed input samples VCF, on a single node with 56 cores & ssd) since most of the work is spent on repartition of annotations vds.

Would be nice to rely on vds already created with a proper number of partitions or to check the current number with n_partitions() before repartitioning.

[1] https://hail.is/docs/0.2/hail.MatrixTable.html#hail.MatrixTable.repartition

**Comment by mpinese** [comment]
Thank you @dnafault, that's a massive speed-up!
